name: SSDLC Actions

on:
  push:
    branches: ["main", "master"]
  pull_request:
    branches: ["main", "master"]

permissions: {}

jobs:
  code-security-analysis:
    permissions:
      security-events: write
    uses: mozilla/ssdlc-actions/.github/workflows/code-security-analysis.yml@792c5a3116d0d279cb92f712058eb0176b33e967
